apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-ez-learning
spec:
  steps:
    - name: build
      image: quay.io/buildah/stable:v1.19.6
      script: |
        buildah bud --file ./Dockerfile --tag quay.io/pfe/ez-learning:latest .
      workingDir: /workspace/source
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
volumes:
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock
