apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-ez-learning
spec:
  steps:
    - name: deploy
      image: 'bitnami/kubectl:latest'
      script: |
        oc set image deployment/ez-learning ez-learning=quay.io/pfe/ez-learning:latest --namespace=pfe

