version: '3.8'

services:
  ez-learning-app:
    image: localhost/ez-learning-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./doc:/app/doc
    environment:
      JAVA_OPTS: "-Xmx512m"

